"""Initial m8 migration

Revision ID: 5c8daafa57bd
Revises: 
Create Date: 2026-09-13 04:06:19.623559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c8daafa57bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_category',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('slug', name='uq_category_slug'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_app_category_id'), 'app_category', ['id'], unique=False)
    op.create_index(op.f('ix_app_category_owner_id'), 'app_category', ['owner_id'], unique=False)
    op.create_table('app_privileged_action_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('action', sa.Enum('add', 'edit', 'delete', name='app_privileged_action'), nullable=False),
    sa.Column('table_name', sa.String(length=128), nullable=False),
    sa.Column('row_pk', sa.String(length=128), nullable=False),
    sa.Column('target_owner_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_app_privileged_action_audit_actor_user_id'), 'app_privileged_action_audit', ['actor_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_privileged_action_audit_actor_user_id'), table_name='app_privileged_action_audit')
    op.drop_table('app_privileged_action_audit')
    op.drop_index(op.f('ix_app_category_owner_id'), table_name='app_category')
    op.drop_index(op.f('ix_app_category_id'), table_name='app_category')
    op.drop_table('app_category')
    # ### end Alembic commands ###
