[mypy]
ignore_missing_imports = True
exclude = (?x)(
    auth_user_service/alembic/versions/
    | examples/fastapi_full/alembic/versions/
    | examples/docker_compose/.*/shared_migrations/.*/versions/
  )
