"""Initial auth migration

Revision ID: 26e421434bed
Revises: 
Create Date: 2026-07-24 11:55:09.783940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '26e421434bed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_privileged_action_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('action', sa.Enum('add', 'edit', 'delete', name='auth_privileged_action'), nullable=False),
    sa.Column('table_name', sa.String(length=128), nullable=False),
    sa.Column('row_pk', sa.String(length=128), nullable=False),
    sa.Column('target_owner_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_privileged_action_audit_actor_user_id'), 'auth_privileged_action_audit', ['actor_user_id'], unique=False)
    op.create_table('auth_revocation_outbox',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('auth_generation', sa.BigInteger(), nullable=False),
    sa.Column('effect_type', sa.String(length=16), nullable=False),
    sa.Column('target_digest', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'auth_generation', 'effect_type', 'target_digest', name='uq_revocation_outbox_effect_target')
    )
    op.create_index(op.f('ix_auth_revocation_outbox_status'), 'auth_revocation_outbox', ['status'], unique=False)
    op.create_index(op.f('ix_auth_revocation_outbox_user_id'), 'auth_revocation_outbox', ['user_id'], unique=False)
    op.create_table('auth_security_policy',
    sa.Column('policy_key', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('policy_key')
    )
    op.create_table('auth_tombstone',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('terminal_generation', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_auth_tombstone_user_id'), 'auth_tombstone', ['user_id'], unique=False)
    op.create_table('auth_user',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('provider', sa.Enum('PASSWORD', 'GOOGLE', name='authprovidertype'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('SUPERADMIN', 'ADMIN', 'WRITER', 'READER', 'USER', name='roletype'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('oauth_user_id', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('telegram_id', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('auth_generation', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("is_superuser = (role = 'SUPERADMIN')", name='ck_user_superuser_role_consistency'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_user_id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_auth_user_email'), 'auth_user', ['email'], unique=True)
    op.create_index(op.f('ix_auth_user_id'), 'auth_user', ['id'], unique=False)
    op.create_index(op.f('ix_auth_user_tenant_id'), 'auth_user', ['tenant_id'], unique=False)
    op.create_table('auth_api_key',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('access_mode', sa.Enum('READ_ONLY', 'READ_WRITE', name='apikeyaccessmode'), server_default='READ_ONLY', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_auth_api_key_id'), 'auth_api_key', ['id'], unique=False)
    op.create_index(op.f('ix_auth_api_key_user_id'), 'auth_api_key', ['user_id'], unique=False)
    op.create_table('auth_client_session',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('provider', sa.Enum('PASSWORD', 'GOOGLE', name='authprovidertype'), nullable=False),
    sa.Column('jwt_jti', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('refresh_token_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('jwt_expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('external_access_token', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('external_refresh_token', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('external_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('auth_generation', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_client_session_id'), 'auth_client_session', ['id'], unique=False)
    op.create_index(op.f('ix_auth_client_session_user_id'), 'auth_client_session', ['user_id'], unique=False)
    op.create_table('auth_api_key_audiences',
    sa.Column('api_key_id', sa.Uuid(), nullable=False),
    sa.Column('audience_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['auth_api_key.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('api_key_id', 'audience_id')
    )
    op.create_table('auth_rate_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('period', sa.Enum('MINUTE', 'HOUR', 'DAY', 'MONTH', name='period'), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.CheckConstraint('api_key_id IS NOT NULL OR user_id IS NOT NULL', name='ck_ratelimit_has_owner'),
    sa.ForeignKeyConstraint(['api_key_id'], ['auth_api_key.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'period', name='uq_ratelimit_api_key_period'),
    sa.UniqueConstraint('user_id', 'period', name='uq_ratelimit_user_period')
    )
    op.create_index(op.f('ix_auth_rate_limit_api_key_id'), 'auth_rate_limit', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_auth_rate_limit_user_id'), 'auth_rate_limit', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_rate_limit_user_id'), table_name='auth_rate_limit')
    op.drop_index(op.f('ix_auth_rate_limit_api_key_id'), table_name='auth_rate_limit')
    op.drop_table('auth_rate_limit')
    op.drop_table('auth_api_key_audiences')
    op.drop_index(op.f('ix_auth_client_session_user_id'), table_name='auth_client_session')
    op.drop_index(op.f('ix_auth_client_session_id'), table_name='auth_client_session')
    op.drop_table('auth_client_session')
    op.drop_index(op.f('ix_auth_api_key_user_id'), table_name='auth_api_key')
    op.drop_index(op.f('ix_auth_api_key_id'), table_name='auth_api_key')
    op.drop_table('auth_api_key')
    op.drop_index(op.f('ix_auth_user_tenant_id'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_email'), table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_index(op.f('ix_auth_tombstone_user_id'), table_name='auth_tombstone')
    op.drop_table('auth_tombstone')
    op.drop_table('auth_security_policy')
    op.drop_index(op.f('ix_auth_revocation_outbox_user_id'), table_name='auth_revocation_outbox')
    op.drop_index(op.f('ix_auth_revocation_outbox_status'), table_name='auth_revocation_outbox')
    op.drop_table('auth_revocation_outbox')
    op.drop_index(op.f('ix_auth_privileged_action_audit_actor_user_id'), table_name='auth_privileged_action_audit')
    op.drop_table('auth_privileged_action_audit')
    # ### end Alembic commands ###
